# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
# exec-once = waybar & hyprpaper & firefox
exec-once = pypr
exec-once = swaync
exec-once = swayosd-server #this is for the volume, brightness etc popup thing
#exec-once = hyprpaper &hyprpaper
#exec-execonce = waypaper --restorei
exec-once = swaybg -i /home/roah/Wallpapers/default/background.png -m fill &
# Select a wallpaper and immediately set it with swaybg
#swaybg -i "$(./hellpaper ~/Wallpapers)" -m fill

exec-once = discord --start-minimized
#exec-once = battery-notify
exec-once = ~/.config/hypr/scripts/battery-watcher.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = hyprlock & hypridle & waybar & nm-applet & blueman-applet
exec-once = kdeconnect-indicator
exec-once = thunderbird --headless
#exec-once = localsend
#exec-once = xfce4-power-manager
