decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 10
    #screen_shader = /home/roah/.config/hypr/Scripts/grayscale.glsl
    blur {
        enabled = true
        size = 15
        passes = 2
	ignore_opacity = true
	noise = 0.01
	contrast = 0.8
	xray = false
	new_optimizations = true
    }
   dim_inactive = false
   active_opacity = 1 
   inactive_opacity = 0.95

}

#Added below from:https://github.com/yugaaank/dotfiles/blob/main/hypr/hyprland/general.conf
decoration {
    # 2 = circle, higher = squircle, 4 = very obvious squircle
    # Clear squircles look really off; we use only extra .4 here to make the rounding feel more continuous
    rounding_power = 2.4
    rounding = 18

    blur {
        enabled = true
        xray = true
        special = false
        new_optimizations = true
        size = 10
        passes = 3
        brightness = 1
        noise = 0.05
        contrast = 0.89
        vibrancy = 0.5
        vibrancy_darkness = 0.5
        popups = false
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }

    shadow {
        enabled = true
        ignore_window = true
        range = 50
        offset = 0 4
        render_power = 10
        color = rgba(00000027)
    }

    # Dim
    dim_inactive = true
    dim_strength = 0.05
    dim_special = 0.07
}
