# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto
monitor=eDP-1, 2880x1800, 0x0, 1.50
#For apps
xwayland {
  force_zero_scaling = true
}
#variable frame rate
vfr= true
